//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCompiler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeSamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeSamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestCompiler.CodeSamples", typeof(CodeSamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TestFixture]
        ///	public class SeleniumTest {{ 
        ///		{0} 
        ///	}}.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestRunner {{ 
        ///	{0} 
        ///}}.
        /// </summary>
        internal static string Namepace {
            get {
                return ResourceManager.GetString("Namepace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Test]
        ///public void {0}() {{
        ///	SeleniumCommandEngine engine=null;
        ///	try
        ///	{{
        ///		engine = new SeleniumCommandEngine(new FirefoxDriver());
        ///		engine
        ///			{1}
        ///			;
        ///	}}
        ///	catch (Exception ex)
        ///	{{
        ///		Assert.IsTrue(false, &quot;command failed - &quot; + ex.Message);
        ///		engine.close();
        ///	}}
        ///	Assert.IsTrue(true);
        ///}}.
        /// </summary>
        internal static string TestMethod {
            get {
                return ResourceManager.GetString("TestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using NUnit.Framework;
        ///using OpenQA.Selenium;
        ///using OpenQA.Selenium.Chrome;
        ///using OpenQA.Selenium.Firefox;
        ///using OpenQA.Selenium.IE;
        ///using SeleniumExecuter;
        ///using SeleniumExecuter.Commands;.
        /// </summary>
        internal static string Using {
            get {
                return ResourceManager.GetString("Using", resourceCulture);
            }
        }
    }
}
